version: '3'

tasks:
  checkpoint:
    dir: scripts
    cmds:
      - npx zx checkpoint.mjs

  download:
    dir: mainrun
    cmds:
      - python3 download_dataset.py

  train:
    # deps: [checkpoint, download]
    deps: [checkpoint]
    dir: mainrun
    cmds:
      - python3 train.py
      
  train-baseline:
    deps: [checkpoint]
    dir: mainrun
    cmds:
      - python3 train.py --config configs/baseline.yaml

  submit:
    deps: [checkpoint]
    dir: scripts
    cmds:
      - npx zx submit.mjs
    